name: Run Breach Report Processor

on:
  schedule:
    # Runs at 7:00 AM UTC (12:30 PM IST) every day from Monday to Saturday.
    - cron: '0 7 * * 1-6'
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create credentials file from Secret
      run: |
        # Use the correct secret name here
        echo "${{ secrets.GCP_SA_KEY }}" > credentials.json

    - name: Run the breach report script
      run: python breach_report_processor.py
