# This file goes in your GitHub repository in the following path:
# .github/workflows/daily-run.yml

name: Daily Report Automation

on:
  # 1. Schedule to run every day at 5:00 AM UTC
  #    (This is 10:30 AM IST)
  schedule:
    - cron: '0 5 * * *'
  
  # 2. Allows you to manually run this workflow from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      # Step 3: Install all required Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Force-reinstall openpyxl and its specific dependencies to ensure a clean install
          # This avoids potential conflicts in the runner environment
          pip install --upgrade --force-reinstall openpyxl==3.1.5 et-xmlfile==2.0.0
          pip install pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # Step 4: Authenticate with Google Cloud
      # This securely takes the secret you'll create (GCP_SA_KEY)
      # and saves it as a temporary 'credentials.json' file for the script to use.
      - name: Authenticate to Google Cloud
        env:
          # This secret name 'GCP_SA_KEY' MUST match the name you create in GitHub
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: echo "$GCP_SA_KEY" > credentials.json

      # Step 5: Run the Python script
      - name: Run the daily automation script
        env:
          # This tells the Python script where to find the credentials file
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: python daily_automation.py

