# .github/workflows/process-gdrive-data.yml

# Name of the GitHub Actions workflow. This is what you'll see in the Actions tab.
name: Process Google Drive Data Daily

# --- Triggers for the workflow ---
on:
  schedule:
    # This is a cron schedule that runs the workflow every day.
    # The time is in UTC. '15 5 * * *' corresponds to 10:45 AM IST.
    - cron: '15 5 * * *'
  
  workflow_dispatch:
    # This line allows you to manually trigger the workflow from the GitHub UI.
    # It's useful for testing or running the process on demand.

# --- Definition of the jobs to be run ---
jobs:
  run-gdrive-processor:
    # The name of the job.
    name: Run GDrive Data Processing Script
    
    # Specifies the type of machine to run the job on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest
    
    # --- Sequence of steps to execute in this job ---
    steps:
      # Step 1: Check out your repository's code
      # This action downloads your code (including the Python script) into the runner.
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      # This action installs a specific version of Python on the runner.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specifies Python version 3.10

      # Step 3: Cache pip dependencies
      # This step speeds up builds by caching packages between runs
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # Create a new cache key whenever requirements.txt changes
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install the required Python libraries
      # This step now uses your requirements.txt file, which is more reliable.
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the Python script for data processing
      # This is the final step where your actual script is executed.
      - name: Run the GDrive processing script
        env:
          # This securely passes your 'GCP_SA_KEY' secret to the script.
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        # Runs the python script you specified
        run: python free_delivery.py
