# .github/workflows/process-gdrive-data.yml

name: Process GDrive Data

on:
  schedule:
    # Runs at 10:45 AM IST (which is 05:15 UTC) every day.
    - cron: '15 5 * * *'
  workflow_dispatch: # Allows you to manually run the workflow

jobs:
  run-gdrive-processor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          # Added new libraries for Google API access
          pip install pandas numpy google-auth-oauthlib google-api-python-client

      - name: Run the GDrive processing script
        env:
          # This securely passes your service account key to the Python script
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        # Ensure the python script file is named 'gdrive_processor.py'
        run: python gdrive_processor.py
